version: '2'
services:
  db:
    build: ./.docker/postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: thajeztah/pgadmin4:1.1
    ports:
      - "5050:5050"
    depends_on:
      - db
    links:
      - db